### ISSUE TITLE
Appveyor build failing

### ISSUE THREAD

**Issue by mohawk2** [PDLPorters/pdl#203]
Recently the Appveyor build is failing with (eg https://ci.appveyor.com/project/zmughal/pdl/build/1.0.449):

```
Download of strawberry-perl-5.20.1.1-64bit.msi (72.78 MB) completed.
WARNING: Missing package checksums are not allowed (by default for HTTP/FTP, 
 HTTPS when feature 'allowEmptyChecksumsSecure' is disabled) for 
 safety and security reasons. Although we strongly advise against it, 
 if you need this functionality, please set the feature 
 'allowEmptyChecksums' ('choco feature enable -n allowEmptyChecksums')
```

@zmughal can you offer a pointer? Does this just need extra config?

**Comment by zmughal** [comment]
Ah, so this is actually an issue with <https://chocolatey.org/packages/StrawberryPerl>. It worked in the past, but the package has not been updated for a long time. We could run the command in that output as a temporary measure (`choco feature enable -n allowEmptyChecksums`), but the real fix would be to update the Chocolatey package since it is now a little over 2 years behind.

**Comment by zmughal** [comment]
If we did want to create an updated Strawberry Perl package, we can use those checksums like this <https://chocolatey.org/docs/helpers-install-chocolatey-package>.

**Comment by amba** [comment]
This should be fixed now with the recent uploads of new choco packages for Strawberry Perl.

**Comment by zmughal** [comment]
Confirming that this is fixed. I re-ran this build and it is working <https://ci.appveyor.com/project/zmughal/pdl/build/1.0.454>. Thank you for the update @amba!

Closing.
