### ISSUE TITLE
PDL::IO::Misc: Undefined subroutine &PDL::Ops::assgn called

### ISSUE THREAD

**Issue by amba** [PDLPorters/pdl#212]
Hey,
If I run (PDL-2.018)
```

#!/usr/bin/env perl
use PDL::IO::Misc;

my @cols = rcols('data.dat', {EXCLUDE => '/^#/'});
```

I get

```
simon@buero ~/perl/lab (master)$ ./rcols.pl
Undefined subroutine &PDL::Ops::assgn called at /home/simon/.plenv/versions/5.24. /lib/perl5/site_perl/5.24.0/x86_64-linux/PDL/Core.pm line 810, <GEN0> line 2.

```

The error disappears when adding `use PDL` or `use PDL::Lite`

**Comment by devel-chm** [comment]
Could you provide a small data.dat that gives the problem?  Thanks.

**Comment by d-lamb** [comment]
The reason that error is coming up is that PDL::Ops is never `use`d directly in Misc.pm.  Since [the docs for PDL::Lite](https://github.com/PDLPorters/pdl/blob/0aa5efaf7633cb9b1d4a5289615edcb1e9221cd8/Basic/Lite.pm#L3-L11) say that PDL::Lite is the minimum required to required to have a working PDL, and that is not present in the example code, I'm going to close this as not-a-bug.
