### ISSUE TITLE
$PDL::doubleformat and $PDL::floatformat are not effective?

### ISSUE THREAD

**Issue by stphnlyd** [PDLPorters/pdl#245]
Below prints 0.333333333333333, and $PDL::doubleformat does not take effect. The same is with $PDL::floatformat. 

```perl
use 5.012;
use PDL;
$PDL::doubleformat = "%.1f";
say pdl(1/3);
```

But those variables are mentioned in the doc. https://metacpan.org/pod/PDL::Core#$PDL::floatformat,-$PDL::doubleformat,-$PDL::indxformat

And actually I see the variables are not used in this PDL::Core::string() method https://github.com/PDLPorters/pdl/blob/master/Basic/Core/Core.pm#L2855

**Comment by d-lamb** [comment]
This is actually not as bad as it first seems.  $PDL::doubleformat and friends work properly on piddles with more than one element:

~~~~perl
$PDL::doubleformat = "%.1f";
print "1D: ", pdl(1,2,3,4)/3
print "2D: ", pdl([1,2,3,4],[5,6,7,8])/3
print pdl(1)/3;

1D:  [0.3 0.7 1 1.3]
2D: 
[
 [0.3 0.7 1.0 1.3]
 [1.7 2.0 2.3 2.7]
]
0.333333333333333
~~~~
It is only in the trivial case of one-element piddles that the formatting fails to take hold.  In this case, PDL lets Perl's formatting rules take over.  This is a good thing because you probably don't want to see this:

~~~~perl
print pdl(2.5)
       2.5
~~~~
but rather
~~~~perl
print pdl(2.5)
2.5
~~~~

**Comment by d-lamb** [comment]
If you want $PDL::doubleformat to be effective for single-element piddles (as opposed to 0-element scalars as I had in the previous comment), then you just need to add some square braces:

~~~~perl
$PDL::doubleformat = "%08.1f"
print pdl([1/3])
[000000.3]
~~~~

**Comment by stphnlyd** [comment]
@d-lamb Thanks for the explaination! Sorry I didn't test it more before I created the ticket. It can be closed.
