### ISSUE TITLE
qsort and qsortvec inconsistent with BAD values

### ISSUE THREAD

**Issue by d-lamb** [PDLPorters/pdl#252]
The docs for qsort state that 'Bad values are moved to the end of the array:'

The docs for qsortvec state nearly the same thing: 'Vectors with bad components should be moved to the end of the array:'

However this does not seem to be borne out in practice in qsortvec.
~~~~
pdl> p $p = pdl("[0 0] [-100 0] [BAD 0] [100 0]")

[
 [   0    0]
 [-100    0]
 [ BAD    0]
 [ 100    0]
]

pdl> p $p->qsortvec

[
 [ BAD    0]
 [-100    0]
 [   0    0]
 [ 100    0]
]

pdl> p $p->((0))->qsort
[-100 0 100 BAD]
~~~~

My expectation is that the output of qsortvec (given the documentation, and the output of the qsort expression) should be:
~~~~
[
 [-100    0]
 [   0    0]
 [ 100    0]
 [ BAD    0]
]
~~~~

**Comment by mohawk2** [comment]
That is also my expectation! `qsortvec` confidently has `HandleBad => 1` and the docs that you note, but doesn't have `BadCode` (or, as you rightly note, correct handling of bad values).

**Comment by mohawk2** [comment]
...and now it (and `qsortveci`) do. Thanks for the report!

**Comment by mohawk2** [comment]
`qsort` inplace with bad values was pretty underfunctional too, now fixed by the above commit. That was masked by the `qsort` testing code largely checking its work with `all($pdl1 == $pdl2)`, and that does not do what you think if either ndarray has badvalues, including in different places from each other, but at least one matching non-bad value. Bad values are a bit like NaN, but not entirely.
