### ISSUE TITLE
Add support for compressed images to wfits

### ISSUE THREAD

**Issue by d-lamb** [PDLPorters/pdl#291]
Currently PDL::IO::FITS::wfits() has the 'compress' option, but it is just a placeholder.

It should be expanded, perhaps by adding schemes to PDL::Compression, to include at least RICE compression.  But others are possible.  See [Tiled Image Compression Convention](https://fits.gsfc.nasa.gov/registry/tilecompression.html).  The [CFITSIO Data Compression page](https://heasarc.gsfc.nasa.gov/docs/software/fitsio/compression.html) may also be helpful.

I'm adding a note to the wfits docs, to note that compression is not yet implemented.  When it is, that note can be removed.

**Comment by mohawk2** [comment]
Turns out PDL::Compression already had RICE (indeed, it has nothing else). Those references were indeed essential, thanks for those! I have now hooked up the code (quite a bit of which was already there) and removed the note.

Please give it a try and report any problems (reopen here, or a new issue, as you prefer :-)
