### ISSUE TITLE
Segfault in t/minuit.t when installing 2.033 from cpan on cygwin

### ISSUE THREAD

**Issue by Jheald** [PDLPorters/pdl#297]
I tried to install PDL-2.033 from cpan on cygwin, but got a fail because of a segmentation fault, apparently in test 5 of t/minuit.t 

Everything installed should be the current versions from cygwin or cpan  (Perl 5.32.1, gfortran 10.2.0, ExtUtils::F77 1.26), as I had just done a full update from cygwin.

I don't think I'm going to need minuit, so I've installed anyway with cpanm --force , but thought I should raise it here.

**Comment by mohawk2** [comment]
Thank you for the report! I'm glad you're able to get done the things you want, but please raise an issue if you can't.

In order to help eliminate this, how do you feel about adding to PDL's CI a Cygwin case, probably based on Perl's own one (https://github.com/Perl/perl5/blob/blead/.github/workflows/testsuite.yml#L376)? And as a stretch goal, also an MSVC case (https://github.com/Perl/perl5/blob/blead/.github/workflows/testsuite.yml#L286)?

**Comment by mohawk2** [comment]
The CI now has a Cygwin case, although it only gets run on releases.

I've just run the Minuit tests under valgrind, and it shows no errors. This means I don't have the means to discover why this happened for you. Without further information, there's nothing I can do.

Therefore, regretfully I am closing this. However if you learn more info, please reopen!
