### ISSUE TITLE
Decompression error reading Rice-compressed FITS files

### ISSUE THREAD

**Issue by d-lamb** [PDLPorters/pdl#355]
When reading a 4k x 4k Rice-compressed FITS file, I get about 1600 lines printed to STDERR that say `rdecomp: decompression error: hit end of compressed byte stream`.  That error comes from the very end of rdecomp in ricecomp.c: https://github.com/PDLPorters/pdl/blob/a0ed35886d5040cdaf86fbac734d228fb7dce39e/Libtmp/Compression/ricecomp.c#L689

That is a very undesirable behavior.  I did a `git bisect` and found that 3a2ea799d2d57b6748372bba781867940e2640a7 is the first bad commit.  The current git master (a0ed35886d5040cdaf86fbac734d228fb7dce39e) also shows this behavior.  Nothing changed in Libtmp/Compression with that commit, but there were changes to zeroes().  In PDL::Compression, rice_expand uses zeroes to allocate the output array.  https://github.com/PDLPorters/pdl/blob/a0ed35886d5040cdaf86fbac734d228fb7dce39e/Libtmp/Compression/compression.pd#L221

Minimum working example, from a directory in which the most recent PDL has been built:
```
curl -O http://suntoday.lmsal.com/sdomedia/SunInTime/2021/12/17/f0171.fits
perl -Mblib -MPDL -E 'rfits("f0171.fits");'
```

**Comment by mohawk2** [comment]
Thanks for the report! I confirm the behaviour of `rfits` changed at the commit you gave. I've corrected the behaviour of `zeroes` which had changed to ignoring the type if given an input ndarray, in https://github.com/PDLPorters/pdl/commit/e340d82e9aaf46c7269fa201a1c24fd102919ba7. It's still giving errors, despite the other inputs looking correct, so more investigation is needed.

**Comment by mohawk2** [comment]
Moments later, I realised the other change since 2.057_01 (routine pthreading), plus something I noticed when looking at the `rdecomp` function: it's not thread-safe because it has a `static` buffer of `nonzero_count`, and all the pthreads are `malloc`-ing and assigning into it.

**Comment by mohawk2** [comment]
The real problem with thread-safety was with the `lbuf` concept (a passed-in ndarray that was only the size of the lowest dim, and the input was manually copied into it, so with pthreading all threads would try to use the same incorrect input buffer), which was being used instead of either `[phys]` on the `in` Par, or simply using `$P(in)` which automatically sets the `phys` (physicalise) property on the given Par. I have fixed all these things and pushed them. Please try the latest `master` version with both compression and decompression and let us know of any problems!

**Comment by d-lamb** [comment]
That fix quiets down the warnings, thanks!  I thought a test would be good but I'm not quite sure how to capture STDERR emitted from a PP call.  The [perlfaq8](https://perldoc.perl.org/perlfaq8#How-can-I-capture-STDERR-from-an-external-command?) shows how to do this for an external command, but it seems not quite the same here.  Any ideas?  This is a better self-contained test that exercises the bug:

```perl
use strict;
use warnings;
use Test::More;
use PDL::LiteF;

use PDL::Compression;
use PDL::Transform;
use PDL::IO::FITS;

my $m51 = rfits('m51.fits');
my $m51_big = $m51->match([384,384,200],{bound=>'extend'});
$m51_big->check_badflag();

my ($y,$xsize ) = $m51_big->rice_compress();
#this is the line that used to cause a print to STDERR
my $m51_big_2 = $y->rice_expand($xsize);
```

**Comment by mohawk2** [comment]
The fact that it was writing to STDERR rather than croaking is a bit misleading; those weren't really warnings, they were errors because of corrupted data. I am fairly confident that if you'd read the resulting data you'd have seen it was incorrect. Basically, I believe that thinking about testing whether STDERR was produced is simply a mistake. You'd therefore change the above to simply check `$m51_big_2` had the correct value.

I think it would also be prudent to supply the compressed file and have the code uncompress it, since only test the round trip rather resembles marking one's own homework.

Also, the PDL::Compression code should probably just `$CROAK()` rather than the misguided `stderr` stuff. Feel like making a PR for all these things? :-)

**Comment by mohawk2** [comment]
I've simplified the above test code and pushed it.

**Comment by mohawk2** [comment]
...and also made the functions return `char *` for error-reporting, and `$CROAK()` with those if not `NULL`. Thanks again!
