### ISSUE TITLE
Interface to GLPK

### ISSUE THREAD

**Issue by jo-37** [PDLPorters/pdl#437]
From my wish list: Are there any chances to have an interface from PDL to GLPK as easy as in Octave? See https://www.gnu.org/software/glpk/ and https://docs.octave.org/latest/Linear-Programming.html

**Comment by mohawk2** [comment]
There certainly are! You can start with one of the GSL modules (that live in `Libtmp` in the main PDL repo), copy that. A quick look at the `glpk.h` suggests you'd need a Perl constructor for the `glp_prob` data structure, then make the various functions that take that as the first param be methods in a package called something like PDL::GLPK, with a fairly literal translation of the C interface.

If you need help, please email one of the PDL mailing lists!

**Comment by jo-37** [comment]
Thanks for encouraging! Did some investigations in the meantime, but I'm not sure about the proper path. The GLPK interface is rather complex, but re-inventing the Octave interface doesn't seem to be a good idea neither. Need some time to think it over.  There is an outdated Math::GLPK module that I couldn't get to work and there is Inline::Octave where its author gave up to bind liboctave with perl.

**Comment by mohawk2** [comment]
If you like the Octave interface, then mimic that instead! If I were doing it myself, I'd start either with the OO approach outlined above, or a very literal translation of the C interface, like the GSL binding, but I'm not, so you do what you feel suitable.

**Comment by jo-37** [comment]
After some PP warmup:
Wrote a working prototype. It was not as complicated as expected. Octave comes with a C-function that is free from any Octave dependencies and that orchestrates all the required GLP functions. Just needed some glue on the PP-side and on the Perl side.

Configuration options are still missing and the function cannot broadcast.

I would extend this prototype to a full-fledged module if there were some principal acceptance for this stuff. It would be great if an PDL expert could take a look at the [prototype](https://github.com/jo-37/pdl-opt-glpk).

**Comment by jo-37** [comment]
Added configuration parameters and documentation.

My question to pdl-porters: May I publish this module unter the name  **`PDL::Opt::GLPK`** at CPAN?

**Comment by mohawk2** [comment]
On behalf of pdl-porters: yes, absolutely! I have some design/implementation thoughts I'll deal with below. But instantly, to go on CPAN you're going to need to ensure the user has GLPK installed, probably with Devel::CheckLib. See `Basic/Core/Makefile.PL` for an example. You might consider making an Alien::GLPK to make this easier.

**Comment by jo-37** [comment]
Thank you for your suggestions! Firstly, the function `glpk` in `glpk_aio.cc` is a verbatim copy from the Octave project. So it was not my decision to make it C++. The whole code in this module is just glue between Perl and the existing C++ function, and most of the glue is ported from C++ (using Octave classes) to C.
Regarding the OtherPars hash: I don't see a problem with handing the hashref into the C function. The corresponding C struct is mandatory as it is an input parameter to the Octave code.
Error handling is still in progress. I need to dig a bit deeper into the matter as this is my first PP resp. XS project. I'll try to understand your  suggestions :-)

I'm not sure if I shall publish the module to CPAN in its current state. At least it is usable and documented. Reworking the error handling would change the interface, though.

**Comment by mohawk2** [comment]
> Thank you for your suggestions! Firstly, the function `glpk` in `glpk_aio.cc` is a verbatim copy from the Octave project. So it was not my decision to make it C++.

You've copied it from there, but now it's in your repo. That means you can change it. It doesn't have any C++ in. Please try deleting the `extern "C" {` stuff, renaming the file (and changing the reference in `Makefile.PL`), and seeing what happens.

> Regarding the OtherPars hash: I don't see a problem with handing the hashref into the C function. The corresponding C struct is mandatory as it is an input parameter to the Octave code.

You can change the Octave code, because it's your code now. There isn't a problem as such, but conceptually I like to keep Perl stuff out of `Code` sections so that transforms (or PDL "operations", same thing) could be used in non-Perl contexts without change. See #358 

> Error handling is still in progress. I need to dig a bit deeper into the matter as this is my first PP resp. XS project. I'll try to understand your suggestions :-)

If you have questions, please ask!

> I'm not sure if I shall publish the module to CPAN in its current state. At least it is usable and documented. Reworking the error handling would change the interface, though.

I'd say since it belongs entirely to you, and is so far only used by you, then any interface changes are fine?

**Comment by jo-37** [comment]
Thanks for your suggestions, that led me to some changes:
 - Stepped back from C++ to C with glpc_aio. My intention was to be able to drop in an updated version from Octave without changes. I realized this was a silly idea.
 - Adjusted the C structure to include all necessary parameters. I still do not see an advantage in __not__ performing the hash-to-struct transformation within C. The parameters match one-to-one by name between the hash and the struct. A "copy-by-name" operation seems possible with C only, as I solved it with the `SETPARM` macro.
 - Moved the type check for the `parms` hash ref into the `PMCode` block. The suggestion to move it into the `HdrCode` block did not word because the `HdrCode` block has no effect if a `PMCode` block is in use. (Didn't find any hints about this in  the docs.)
 - Removed the `errnum` from the output arguments by translating glp error numbers to their textual representation and using these for the PDL_err message.
 - Published [PDL::Opt::GLPK](https://metacpan.org/pod/PDL::Opt::GLPK)
 
Thank you very much for your support! May I contact you if I have further questions? (Reopen the issue?)

Closing this issue as the basic goal was achieved.

**Comment by mohawk2** [comment]
I support you leaving it open if you'd like, but also if you'd like to close it.

- I don't think it's a silly idea to want to drop-in Octave code, but the cost of supporting C++ here would to me have outweighed any likely benefit
- Remember that XS is C, and that the hash-ref is an exclusively Perl thing. In a perfect world, the PDL binding of this would work when PDL is made available as a Python library. I think using a macro to solve this sort of thing is a great idea, specifically here an "X macro" (see https://www.perlmonks.org/?node_id=11151470). Another way to deal with this would be to move your C calling code into the `Code` section, as already advocated, because then you could use Perl code to generate the C struct, the parsing code, and/or the `OtherPars`

The best way to get support would be to join one or both of the `pdl-{general,devel}` mailing lists (https://pdl.perl.org/?page=mailing-lists), to reach a wider base of people with undoubtedly more knowledge than me.

Finally, `HdrCode` should either work when there's a `PMCode`, or be documented as not doing so (but the first is better). Feel like opening an issue so that doesn't get forgotten? Also, feel like having a go at making PDL::PP actually support that? I don't think it would be very tricky.
