### ISSUE TITLE
"clump" can produce ndarrays with unexpected behaviour

### ISSUE THREAD

**Issue by vadim-160102** [PDLPorters/pdl#461]
```
pdl> $x = zeroes 3,2; $y = $x-> clump( 2 )
pdl> $x .= 3
pdl> p $y
[3 3 3 3 3 3]
pdl> $x = zeroes 3,2; $y = $x-> clump( 2 )
pdl> $z = $y + 1; $x .= 3
pdl> p $y
[3 3 3 3 3 3]
```

So far so good. But if "clump" is called with a list of dims, rather than their count:

```
pdl> $x = zeroes 3,2; $y = $x-> clump( 0,1 )
pdl> $x .= 3
pdl> p $y
[3 3 3 3 3 3]
pdl> $x = zeroes 3,2; $y = $x-> clump( 0,1 )
pdl> $z = $y + 1; $x .= 3
pdl> p $y
[0 0 0 0 0 0]
```
Simply accessing the "$y" to e.g. calculate some other "$z" (or just to print the "$y" to REPL, etc.) seems to disrupt the dataflow from "$x" to "$y".

Further illustration requires higher dimensions, and, intuitively, feels like another facet of the same bug:

```
pdl> $x = zeroes 2,3,4; $y = $x-> clump( 1,2 )
pdl> $x .= 3
pdl> p $y-> uniqvec

[
 [3 3]
]

pdl> $x = zeroes 2,3,4; $y = $x-> clump( 1,2 )
pdl> $y .= 3
pdl> p $y-> uniqvec

[
 [0 0]
]
```

**Comment by mohawk2** [comment]
Thanks for the report! I'm extremely pleased to say that this is actually fixed already on `master`, in d3a79078535cc6acf7f3f59066f2ee146c1f09e1. Could you give it a go and confirm you agree?

**Comment by vadim-160102** [comment]
The "further illustration" i.e. a fragment with `uniqvec ` runs now as expected i.e. fixed. But issue which involves "touching" clumped ndarray is not fixed, i.e. the same output:
```
pdl> $x = zeroes 3,2; $y = $x-> clump( 0,1 )
pdl> $z = $y + 1; $x .= 3
pdl> p $y
[0 0 0 0 0 0]
```

**Comment by mohawk2** [comment]
Thank you for the feedback!

I'm working on a fix for a similar issue, shown in https://www.perlmonks.org/?node_id=11153348. Once I have a fix for that, I will see if it also fixes this, and if not, then have a go at that too.

**Comment by mohawk2** [comment]
To avoid doubt: d3a79078535cc6acf7f3f59066f2ee146c1f09e1 already fixes 2 of the 3 cases shown above.

**Comment by mohawk2** [comment]
Your testcase can be simplified to (with nice graph imagery, you need the latest `git master` of PDL, plus GraphViz2 installed on your Perl):

```perl
$RUN = 'a';
$x = zeroes 3,2;
$y = $x-> clump( 0,1 ); gv $x, "o${RUN}1.png";
$y->make_physvaffine; gv $x, "o${RUN}2.png";
$x .= 3; gv $x, "o${RUN}3.png";
p $y; gv $x, "o${RUN}4.png";
```

I had `$RUN` set as "a" with the commit before the hopefully-fixing commit, then ran it again with the fixing commit setting it to "b". The output image, being run through `montage o*.png -tile 4x2 -geometry '1x1<' montage.png`, is attached:
![montage](https://github.com/PDLPorters/pdl/assets/7308181/ec9b8f69-b587-4a5a-a3c2-996c3d35b89c)
It illustrates the before (above) and after (below) evolution (left to right) of the above statements.

The problem was because all outputs of a "vaffine" transformation got set as `DATACHANGED`, including the `broadcastI`/`unbroadcast` combo used by `clump(multidims)`. When the output of `clump` (`$y`) gets evaluated, its input gets its data allocated and set, even though it's a "vaffine" output, so it's not lazy enough yet (that's another problem I identified in investigating this). When the "root" ndarray gets assigned to, the `DATACHANGED` "message" was getting stopped at the output of `broadcastI` (which acted as a sort of "umbrella"), so the `$y` variable never learned it needed to re-read its dataflowing input.

My addition to Karl's test case shows there's still a small problem, so I'll keep fixing it before pushing, but the above captures what's going on.

**Comment by mohawk2** [comment]
I attach the montage from the same code with before and the updated-after:
![montage](https://github.com/PDLPorters/pdl/assets/7308181/be0a6b27-11c3-4ba7-80ef-1962c16901a5)

The remaining problem was in the third image, bottom row: after mutating the "root", its first child (what I'm calling a "vaffine in waiting", since its vaffine flag and data structures haven't been set up at that point) was still getting its `DATACHANGED` flag set, which is wrong. As you can see above, that's now not the case.

@vadim-160102 Please could you try the latest `git master` and see if it works for you? If it does, please close this issue.

**Comment by vadim-160102** [comment]
Many thanks for your effort! I can confirm, issues as stated in the original ticket are fixed now, but I hesitate to close it. It's easy to come up with just another variety:
```
pdl> $x = zeroes 2,2,2; $y = $x-> clump( 0,1 )-> clump( 0,1 )
pdl> $x .= 3; p $y
[3 3 3 3 3 3 3 3]
pdl> $x = zeroes 2,2,2; $y = $x-> clump( 0,1 )-> clump( 0,1 )
pdl> $z = $y + 1;
pdl> $x .= 3; p $y
[0 0 0 0 0 0 0 0]
```
In fact I have yet to grasp what these beautiful images mean, and am not sure at all if the latest example is practically significant. Worse, I have no rigorous system for testing, but simply something off the top of my head. Please feel free to close the issue, if such convoluted examples aren't supposed to work.

**Comment by mohawk2** [comment]
Thank you for your continued vigilance on this! I don't want this closed until you agree that it's really fixed, and clearly it isn't yet.

The effect here that assignment to `$z` has is to `make_physvaffine` `$y`, so I use that in the repro code rather than introducing an extra variable. The "benefit" (believe it or not) of having `clump` here, is that it's not yet a vaffine transformation, just a normal data-flowing one, which means it definitely gets allocated memory and needs the `DATACHANGED` message system to work right. Clearly the previous partial fix addressed those messages getting passed, as can be seen here. The repro code for the problematic case is (I omit your first one which works, since it doesn't allocate memory at a point that interferes, and therefore doesn't reveal the problem):

```perl
$run = 'b'; $vaff_before_assign = 1;
$x = zeroes 2,2,2; $y = $x-> clump( 0,1 )-> clump( 0,1 );
gv $x, "o${run}1.png";
$y->make_physvaffine if $vaff_before_assign;
gv $x, "o${run}2.png";
$x .= 3;
gv $x, "o${run}3.png";
$y->make_physvaffine;
gv $x, "o${run}4.png";
```
![montageb](https://github.com/PDLPorters/pdl/assets/7308181/85fd2e6c-978e-4c01-bf85-a0105f8443ae)

Each column is one of the `gv`-ed images:
- 1 is the complicated structure, unchanged/unevaluated
- 2 is after the bottom ndarray gets "evaluated", and all its parents get materialised/vaffined/allocated
- 3 is after the top one gets assigned to, and you can see `DATACHANGED` on all the ndarrays downwards (except "vaffine in waiting" ones, which get bypassed by those vaffine arrows)
- 4 is after the bottom one gets evaluated, which reads its parent, and that is supposed to carry on recursively up until it runs out of `DATACHANGED`; you can see it stops partway up on one that has `DATACHANGED` still, and 0s in its values; that's why the bottom one has 0s

The good news is that this should be easy to capture using the tools in the `t/slice.t` tests already made for the previous iteration, and therefore to fix and keep it fixed.

**Comment by mohawk2** [comment]
The above should fix it (as shown in the test cases based on your code). This diagram is the updated evolution of the ndarrays:
![montageb](https://github.com/PDLPorters/pdl/assets/7308181/b4324a32-19cc-43cd-9148-f54507b6ef80)

Does that now seem fixed to you (on `master`)? Can you think of any further contorted cases? :-)

**Comment by vadim-160102** [comment]
Examples in this thread, plus a couple more as contorted as I could imagine, all work now as expected, so I'm closing the issue. Thank you!
