### ISSUE TITLE
$x .= $x->index(...) leads to "Not physical but doesn't have parent at ufunc.pd" when used later

### ISSUE THREAD

**Issue by djerius** [PDLPorters/pdl#467]
Howdy,

The following code used to work back in the day (2.016?), but now fails.

```
Loaded PDL v2.084 (supports bad values)
pdl> $x = sequence(1000)

pdl> $idx = random( $x->nelem) * $nelem

pdl> $x .= $x->index($idx);

pdl> p $x->min
PDL Not physical but doesn't have parent at ufunc.pd line 564.
        PDL::min(PDL=SCALAR(0x1fffdc8)) called at (eval 218) line 4
        main::__ANON__() called at /home/dj/.plenv/x86_64-linux_RHEL-8/versions/5.38-mst/bin/perldl line 682
        eval {...} called at /home/dj/.plenv/x86_64-linux_RHEL-8/versions/5.38-mst/bin/perldl line 682
        main::eval_and_report("p \$x->min\x{a}") called at /home/dj/.plenv/x86_64-linux_RHEL-8/versions/5.38-mst/bin/perldl line 618
        main::process_input() called at /home/dj/.plenv/x86_64-linux_RHEL-8/versions/5.38-mst/bin/perldl line 638
        eval {...} called at /home/dj/.plenv/x86_64-linux_RHEL-8/versions/5.38-mst/bin/perldl line 638
```

**Comment by mohawk2** [comment]
I just tried this with latest `master`. It worked fine. Can you confirm which version of PDL you tried this with?

**Comment by mohawk2** [comment]
The error shown did happen while I was fixing the `DATACHANGED` propagation, and was caused by that being propagated to the output (aka child) of a non-flowing operation (like here, `.=` aka `assgn`). The fix was to not propagate to non-flowing output `trans`es: https://github.com/PDLPorters/pdl/blob/0e4e6cb39455ee0d300a54de633ff2abe5413960/Basic/Core/pdlapi.c#L870

That worked because `make_physical` shortcuts if the ndarray doesn't have `DATACHANGED` set, as there's nothing to do.

**Comment by mohawk2** [comment]
You can prove this yourself by updating to the latest `master`, which includes the test you show here, and deleting line 870 of `pdlapi.c`, as I just tried, and seeing the test fail, as I just saw. It looks like you are reporting a bug that doesn't exist. Please be careful about that.
